#:Config Curl
#--no-show-error
#--show-error
--parallel
--parallel-max 5
--silent
--fail
--insecure
--location
--retry 6
--retry-delay 3
--retry-all-errors
--retry-connrefused
--max-time 60
--compressed
--header 'Pragma: no-cache'
--header 'Cache-Control: no-cache'
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
--user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'