#!/usr/bin/python3.8
# -*- coding: utf-8 -*-
# region Imports
import sys
from mysql.connector import connect
from os import environ
from time import sleep
cnx_conf={'host':'51.81.34.90', 'user':'root', 'passwd':environ['PWD_DB'], 'database':'db_wsapp', 'port':'3606'}
#cnx_conf={'host':'51.81.34.90', 'user':'root', 'passwd':environ['PWD_DB'], 'database':'db_wsapp', 'port':'3606', 'charset':'utf8mb4', 'collation':'utf8mb4_general_ci'}
#cnx_conf={'host':'51.81.34.90', 'user':'root', 'passwd':environ['PWD_DB'], 'database':'db_wsapp', 'port':'3606', 'charset':'utf8mb4', 'collation':'utf8mb4_0900_ai_ci'}
# endregion

#:Class MySql
class Mysql:
	#:Init
	def __init__(self, conf=None) -> None:
		self.conf, self.cnx, self.cur = None, None, None
		self.conf = conf if (conf) else cnx_conf
		self.conf.update({'connect_timeout':30, 'autocommit':False, 'use_pure':False})
		if ( self.conf.get('port',None) == None ): self.conf.update({'port':'3606'})
		#if ( str(uname()[1]).strip() in list(['bigonha','srv-itcloud-02']) ): self.conf.update({'use_pure':True})

	#:Del
	def __del__(self) -> None:
		self.__close()
		try: del self
		except: pass
		try: sys.modules[__name__].__dict__.clear()
		except: pass

	#:Close
	def __close(self) -> None:
		try: self.cur.close()
		except: pass
		try: self.cnx.close()
		except: pass

	#:Exec
	def Exec(self, sql:str, args=None, commit=False, records=None, buffered=True) -> list:
		try:
			for _ in range(6):
				try:
					with connect(**self.conf) as self.cnx:
						#print(self.conf, self.cnx.charset, self.cnx.collation)
						with self.cnx.cursor(dictionary=True, buffered=buffered) as self.cur:
							results=self.cur.execute(sql.strip(), params=args, multi=True)
							records=[ result.fetchall() for result in results if result.with_rows ]
							if ( commit ): self.cnx.commit()
							#if ( cursor.rowcount < 0 ): records=cursor.fetchall()
							self.cur.close()
						self.cnx.close()
				except: sleep(2)
				else: return(records)
			else: raise
		except: raise Exception('Failed: Exec')
#:END
