[program:rotinas-iot]
command=/usr/bin/python3.8 -u '/mnt/Data/08_GitHub/servers/global/rotinas-iot.py'
directory=/mnt/Data/08_GitHub/servers/global
startsecs=5                                   ; tempo antes de considerar o processo estavel
startretries=20                               ; numero de tentativas para iniciar o programa antes de marcá-lo como "FAILED"
stopwaitsecs=10                               ; tempo de espera para o encerramento
autostart=true                                ; iniciar automaticamente com o Supervisor
autorestart=true                              ; reiniciar automaticamente se falhar
redirect_stderr=true                          ; redireciona a saida de erro stderr para a saida padrão stdout_logfile
stdout_logfile=/tmp/rotinas-iot.log           ; arquivo de log de saída
numprocs=1                                    ; numero de instâncias do processo
user=root                                     ; usuário que rodará o processo
exitcodes=0                                   ; considera os códigos de saida de sucesso