; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                      ; sockef file mode (default 0700)
username=cotta
password=cotta
chown=root:root

[supervisord]
logfile=/var/log/supervisor/supervisord.log   ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid              ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor               ; ('AUTO' child log dir, default $TEMP)
user=root
environment=PYTHON=/usr/bin/python3.8,PYTHONPATH=/mnt/Data/08_GitHub/servers/global/pkg,PYTHONIOENCODING=utf-8,PYTHONOPTIMIZE=0,PYTHONUNBUFFERED=1

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock     ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf


# systemctl daemon-reload; systemctl restart supervisor.service;
# systemctl is-enabled supervisor.service;
# systemctl is-enabled ananicy;
# systemctl daemon-reload;
# systemctl enable supervisor.service;
# systemctl disable supervisor.service;
# systemctl restart supervisor.service;
# supervisorctl -ucotta -pcotta reread; supervisorctl -ucotta -pcotta update; supervisorctl -ucotta -pcotta status;
# supervisorctl -ucotta -pcotta reread; supervisorctl -ucotta -pcotta update; supervisorctl -ucotta -pcotta clear all; supervisorctl -ucotta -pcotta reload; supervisorctl -ucotta -pcotta status;
# supervisorctl -ucotta -pcotta status restart all;
# supervisorctl -ucotta -pcotta restart rotinas-iot;
# truncate -s 0 /tmp/rotinas-iot.log;
# systemctl restart supervisor.service; sleep 3; supervisorctl -ucotta -pcotta status;
